version: '3.8'

services:
  pipeline-controller:
    hostname: ohs-pipeline-controller
    image: us-docker.pkg.dev/cloud-build-fhir/fhir-analytics/main:latest
    volumes:
      - dwh:/dwh
    networks:
      - openhealthstack
      - hapi-fhir
      - default
    configs:
      - source: application.yaml
        target: /app/config/application.yaml
      - source: flink-conf.yaml
        target: /app/config/flink-conf.yaml
      - source: hapi-postgres-config_local.json
        target: /app/config/hapi-postgres-config_local.json
      - source: thriftserver-hive-config_local.json
        target: /app/config/thriftserver-hive-config_local.json

configs:
  application.yaml:
    file: ${PIPELINE_CONFIG}/application.yaml
    name: application.yaml
  flink-conf.yaml:
    file: ${PIPELINE_CONFIG}/flink-conf.yaml
    name: flink-conf.yaml
  hapi-postgres-config_local.json:
    file: ${PIPELINE_CONFIG}/hapi-postgres-config_local.json
    name: hapi-postgres-config_local.json
  thriftserver-hive-config_local.json:
    file: ${PIPELINE_CONFIG}/thriftserver-hive-config_local.json
    name: thriftserver-hive-config_local.json

networks:
  openhealthstack:
    external: true
    name: openhealthstack_public
  hapi-fhir:
    name: hapi-fhir
    external: true

volumes:
  dwh:
    name: dwh
    external: true